dist: xenial
language: node_js
node_js:
  - lts/*
  - 10
cache:
  directories:
    - protocol/node_modules
    - adapters/fiat-gateway-paypal/node_modules

# env:
#   - CLIENT_ID:
#       secure: ""
#   - CLIENT_SECRET:
#       secure: ""

script:
  - cd protocol
  - npm ci
  - npm test
  - cd ../adapters/fiat-gateway-paypal
  - yarn install
  - yarn run build
  # - npm test # once encrypted api key env vars are installed
